web/router.ex
defmodule FlamingPlanet.Router do
  use FlamingPlanet.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug FlamingPlanet.Auth, repo: FlamingPlanet.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FlamingPlanet do
    pipe_through :browser
    get "/", PageController, :index
    resources "/admin", AdminController, only: [:show], singleton: true

    get "/login", SessionController, :new
    resources "/sessions", SessionController, only: [:create, :delete]
  end

  scope "/", FlamingPlanet.Api do
    pipe_through :api
    resources "/daily_tasks", DailyTaskController, only: [:index]
    resources "/inspirations", InspirationController, only: [:index]
    resources "/donations", DonationController, only: [:index]
    resources "/government_actions", GovernmentActionController, only: [:index]
    resources "/news_items", NewsItemController, only: [:index]
  end

  scope "/manage", FlamingPlanet.Manage, as: :manage do
    pipe_through :browser
    resources "/daily_tasks", DailyTaskController, except: [:show]
    resources "/inspirations", InspirationController, except: [:show]
    resources "/donations", DonationController, except: [:show]
    resources "/government_actions", GovernmentActionController, except: [:show]
    resources "/news_items", NewsItemController, except: [:show]
  end
end

web/views/layout_view.ex
defmodule FlamingPlanet.LayoutView do
  use FlamingPlanet.Web, :view

  @doc """
  Generates name for the JavaScript view we want to use
  in this combination of view/template.
  """
  def js_view_name(conn, view_template) do
    [view_name(conn), template_name(view_template)]
    |> Enum.map(fn str -> String.split(str, "_") end)
    |> List.flatten
    |> Enum.reverse
    |> List.insert_at(0, "view")
    |> Enum.map(&String.capitalize/1)
    |> Enum.reverse
    |> Enum.join("")
  end

  # Takes the resource name of the view module and removes the
  # the ending *_view* string.
  defp view_name(conn) do
    conn
    |> view_module
    |> Phoenix.Naming.resource_name
    |> String.replace("_view", "")
  end

  # Removes the extion from the template and reutrns
  # just the name.
  defp template_name(template) when is_binary(template) do
    template
    |> String.split(".")
    |> Enum.at(0)
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FlamingPlanet</title>
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body data-js-view-name="<%= js_view_name(@conn, @view_template) %>">
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <img src="http://drt911.com/wp-content/uploads/2014/07/Fire-Icon-Website.png" alt="fire" height="60" width="50">
          <img src="http://drt911.com/wp-content/uploads/2014/07/Fire-Icon-Website.png" alt="fire" height="60" width="50">
          <img src="http://drt911.com/wp-content/uploads/2014/07/Fire-Icon-Website.png" alt="fire" height="60" width="50">
          <ol class="nav nav-pills pull-right">
            <%= if @current_admin do %>
              <li><%= link "#{ @current_admin.username }", to: admin_path(@conn, :show) %></li>
              <li><%= link "Log out", to: session_path(@conn, :delete, @current_admin), method: "delete" %></li>
            <% end %>
          </ol>
        </nav>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/layout/main.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>FlamingPlanet</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Heebo">
    <link href="https://fonts.googleapis.com/css?family=Francois+One" rel="stylesheet">
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body class="main-view" data-js-view-name="<%= js_view_name(@conn, @view_template) %>">
    <div class="container">
      <header class="custom-header">
        <div class="left">
          <a target="_blank" href="https://www.youtube.com/watch?v=kCpjgl2baLs">Oh no!</a>
        </div>
        <div>
          <img src="http://drt911.com/wp-content/uploads/2014/07/Fire-Icon-Website.png" alt="fire" height="40" width="40">
          <span class="trouble-message"><em>THIS IS BAD. What do we do?!</em></span>
          <img src="http://drt911.com/wp-content/uploads/2014/07/Fire-Icon-Website.png" alt="fire" height="40" width="40">
        </div>
        <div class="right">
          <a target="_blank" href="https://xkcd.com/1732/">We're doomed!</a>
        </div>
      </header>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <div class="footer">
      <div class="container">
        <div class="copyright">
          © FlamingPlanet Productions 2017
        </div>
        <div class="kitten-footer">
          <a target="_blank" href="https://www.buzzfeed.com/chelseamarshall/best-kitten-pictures">Depressed? Have some kittens!</a>
        </div>
      </div>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>